[features]
resolution = true
skip-lint = false

[programs.localnet]
voter_registration = "5xTrnDs8kmZKQ167N9P7UpauYRjVmHJorEecQonadHf3"
voting_system = "7mq1XuSQtpsi2sAWR9hEoYySGDQ9KprgxiUSNXsNjpvq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/new_id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
